"""initial schema

Revision ID: e92deed7795c
Revises: 
Create Date: 2026-03-06 10:12:02.564172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e92deed7795c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_simulation_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('disposition', sa.Text(), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("agent_type IN ('job_seeker', 'recruiter', 'hiring_manager')", name='ck_agents_agent_type'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('growth_stage', sa.String(length=20), nullable=False),
    sa.Column('culture_description', sa.Text(), nullable=False),
    sa.Column('budget_flexibility', sa.String(length=20), nullable=False),
    sa.Column('responsiveness_pattern', sa.String(length=20), nullable=False),
    sa.Column('base_response_delay', sa.Integer(), nullable=False),
    sa.Column('response_delay_variance', sa.Integer(), nullable=False),
    sa.Column('rejection_specificity', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("budget_flexibility IN ('rigid', 'moderate', 'flexible')", name='ck_companies_budget_flexibility'),
    sa.CheckConstraint("growth_stage IN ('early', 'scaling', 'mature')", name='ck_companies_growth_stage'),
    sa.CheckConstraint("industry IN ('technology', 'finance', 'healthcare', 'retail', 'media', 'education', 'manufacturing', 'consulting')", name='ck_companies_industry'),
    sa.CheckConstraint("rejection_specificity IN ('high', 'moderate', 'low')", name='ck_companies_rejection_specificity'),
    sa.CheckConstraint("responsiveness_pattern IN ('fast', 'slow', 'unpredictable', 'ghosts')", name='ck_companies_responsiveness_pattern'),
    sa.CheckConstraint("size IN ('startup', 'mid', 'enterprise')", name='ck_companies_size'),
    sa.CheckConstraint('base_response_delay >= 1', name='ck_companies_base_response_delay'),
    sa.CheckConstraint('response_delay_variance < base_response_delay', name='ck_companies_variance_lt_delay'),
    sa.CheckConstraint('response_delay_variance >= 0', name='ck_companies_response_delay_variance'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('round_number >= 0', name='ck_events_round_number'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_run_round', 'events', ['run_id', 'round_number'], unique=False)
    op.create_table('hiring_managers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('team_situation', sa.String(length=20), nullable=False),
    sa.Column('management_style', sa.String(length=20), nullable=False),
    sa.Column('technical_bar', sa.Text(), nullable=False),
    sa.Column('interview_capacity_per_round', sa.Integer(), nullable=False),
    sa.Column('past_hiring_description', sa.Text(), nullable=False),
    sa.Column('feedback_clarity', sa.String(length=20), nullable=False),
    sa.CheckConstraint("feedback_clarity IN ('clear', 'vague', 'contradictory')", name='ck_hiring_managers_feedback_clarity'),
    sa.CheckConstraint("management_style IN ('detailed_feedback', 'vague', 'responsive', 'slow', 'micromanager')", name='ck_hiring_managers_management_style'),
    sa.CheckConstraint("team_situation IN ('understaffed', 'stable', 'growing', 'rebuilding')", name='ck_hiring_managers_team_situation'),
    sa.CheckConstraint('interview_capacity_per_round >= 0', name='ck_hiring_managers_interview_capacity'),
    sa.CheckConstraint('team_size >= 0', name='ck_hiring_managers_team_size'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('hiring_manager_id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('salary_range_low', sa.Integer(), nullable=True),
    sa.Column('salary_range_high', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=False),
    sa.Column('round_posted', sa.Integer(), nullable=False),
    sa.Column('round_expires', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_ghost', sa.Boolean(), nullable=False),
    sa.Column('actual_budget', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("seniority IN ('junior', 'mid', 'senior', 'lead', 'staff')", name='ck_job_postings_seniority'),
    sa.CheckConstraint("status IN ('open', 'closed', 'filled', 'expired')", name='ck_job_postings_status'),
    sa.CheckConstraint('round_posted >= 0', name='ck_job_postings_round_posted'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_seekers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('education_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('perceived_skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('self_awareness', sa.String(length=20), nullable=False),
    sa.Column('communication_ability', sa.String(length=20), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_seniority', sa.String(length=20), nullable=False),
    sa.Column('target_comp_low', sa.Integer(), nullable=False),
    sa.Column('target_comp_high', sa.Integer(), nullable=False),
    sa.Column('location_flexibility', sa.String(length=20), nullable=False),
    sa.Column('remote_preference', sa.String(length=20), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.Column('burn_rate', sa.Integer(), nullable=False),
    sa.CheckConstraint("communication_ability IN ('strong', 'average', 'weak')", name='ck_job_seekers_communication_ability'),
    sa.CheckConstraint("location_flexibility IN ('rigid', 'moderate', 'flexible')", name='ck_job_seekers_location_flexibility'),
    sa.CheckConstraint("remote_preference IN ('remote_only', 'hybrid', 'onsite', 'no_preference')", name='ck_job_seekers_remote_preference'),
    sa.CheckConstraint("self_awareness IN ('accurate', 'overconfident', 'underconfident')", name='ck_job_seekers_self_awareness'),
    sa.CheckConstraint("target_seniority IN ('junior', 'mid', 'senior', 'lead', 'staff')", name='ck_job_seekers_target_seniority'),
    sa.CheckConstraint('burn_rate > 0', name='ck_job_seekers_burn_rate'),
    sa.CheckConstraint('experience_years >= 0', name='ck_job_seekers_experience_years'),
    sa.CheckConstraint('savings >= 0', name='ck_job_seekers_savings'),
    sa.CheckConstraint('target_comp_high >= 0', name='ck_job_seekers_target_comp_high'),
    sa.CheckConstraint('target_comp_low <= target_comp_high', name='ck_job_seekers_comp_range'),
    sa.CheckConstraint('target_comp_low >= 0', name='ck_job_seekers_target_comp_low'),
    sa.ForeignKeyConstraint(['id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('current_workload', sa.Integer(), nullable=False),
    sa.CheckConstraint("experience_level IN ('junior', 'mid', 'senior')", name='ck_recruiters_experience_level'),
    sa.CheckConstraint('current_workload >= 0', name='ck_recruiters_current_workload'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflections',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('round_number >= 0', name='ck_reflections_round_number'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state_snapshots',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('round_number >= 0', name='ck_state_snapshots_round_number'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'agent_id', 'round_number', name='uq_state_snapshots_run_agent_round')
    )
    op.create_table('cover_letter_versions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('round_created', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('target_posting_id', sa.Uuid(), nullable=False),
    sa.Column('state_summary_at_creation', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("trigger IN ('initial', 'tailored')", name='ck_cover_letter_versions_trigger'),
    sa.CheckConstraint('round_created >= 0', name='ck_cover_letter_versions_round_created'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_versions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('round_created', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('target_posting_id', sa.Uuid(), nullable=True),
    sa.Column('state_summary_at_creation', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("trigger IN ('initial', 'general_rewrite', 'tailored')", name='ck_resume_versions_trigger'),
    sa.CheckConstraint('round_created >= 0', name='ck_resume_versions_round_created'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seeker_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('recruiter_id', sa.Uuid(), nullable=False),
    sa.Column('resume_version_id', sa.Uuid(), nullable=False),
    sa.Column('cover_letter_version_id', sa.Uuid(), nullable=True),
    sa.Column('round_submitted', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_updated_round', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'reviewed', 'rejected', 'advanced', 'ghosted')", name='ck_applications_status'),
    sa.CheckConstraint('round_submitted >= 0', name='ck_applications_round_submitted'),
    sa.ForeignKeyConstraint(['cover_letter_version_id'], ['cover_letter_versions.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['seeker_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('interviewer_id', sa.Uuid(), nullable=False),
    sa.Column('interviewer_type', sa.String(length=20), nullable=False),
    sa.Column('round_scheduled', sa.Integer(), nullable=False),
    sa.Column('round_conducted', sa.Integer(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interviewer_evaluation', sa.Text(), nullable=True),
    sa.Column('candidate_evaluation', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("interviewer_type IN ('recruiter', 'hiring_manager')", name='ck_interviews_interviewer_type'),
    sa.CheckConstraint("outcome IN ('advanced', 'rejected', 'undecided')", name='ck_interviews_outcome'),
    sa.CheckConstraint('round_conducted >= 0', name='ck_interviews_round_conducted'),
    sa.CheckConstraint('round_scheduled >= 0', name='ck_interviews_round_scheduled'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('round_extended', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Integer(), nullable=False),
    sa.Column('additional_benefits', sa.Text(), nullable=True),
    sa.Column('total_comp', sa.Integer(), nullable=True),
    sa.Column('negotiation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_outcome', sa.String(length=20), nullable=False),
    sa.Column('round_resolved', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("final_outcome IN ('accepted', 'declined', 'negotiating')", name='ck_offers_final_outcome'),
    sa.CheckConstraint('base_salary > 0', name='ck_offers_base_salary'),
    sa.CheckConstraint('round_extended >= 0', name='ck_offers_round_extended'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_hm_messages',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('round_sent', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('related_application_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("message_type IN ('candidate_forward', 'feedback', 'nudge', 'role_change_request')", name='ck_recruiter_hm_messages_message_type'),
    sa.CheckConstraint('round_sent >= 0', name='ck_recruiter_hm_messages_round_sent'),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['related_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_hm_messages')
    op.drop_table('offers')
    op.drop_table('interviews')
    op.drop_table('applications')
    op.drop_table('resume_versions')
    op.drop_table('cover_letter_versions')
    op.drop_table('state_snapshots')
    op.drop_table('reflections')
    op.drop_table('recruiters')
    op.drop_table('job_seekers')
    op.drop_table('job_postings')
    op.drop_table('hiring_managers')
    op.drop_index('ix_events_run_round', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_table('events')
    op.drop_table('companies')
    op.drop_table('agents')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
