"""Renamed seekers to job_seekers

Revision ID: f6c190771d57
Revises: e92deed7795c
Create Date: 2026-03-11 16:50:09.340193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c190771d57'
down_revision: Union[str, Sequence[str], None] = 'e92deed7795c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_seeker_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('applications_seeker_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'agents', ['job_seeker_id'], ['id'])
    op.drop_column('applications', 'seeker_id')
    op.add_column('cover_letter_versions', sa.Column('job_seeker_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('cover_letter_versions_seeker_id_fkey'), 'cover_letter_versions', type_='foreignkey')
    op.create_foreign_key(None, 'cover_letter_versions', 'agents', ['job_seeker_id'], ['id'])
    op.drop_column('cover_letter_versions', 'seeker_id')
    op.add_column('resume_versions', sa.Column('job_seeker_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('resume_versions_seeker_id_fkey'), 'resume_versions', type_='foreignkey')
    op.create_foreign_key(None, 'resume_versions', 'agents', ['job_seeker_id'], ['id'])
    op.drop_column('resume_versions', 'seeker_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('seeker_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resume_versions', type_='foreignkey')
    op.create_foreign_key(op.f('resume_versions_seeker_id_fkey'), 'resume_versions', 'agents', ['seeker_id'], ['id'])
    op.drop_column('resume_versions', 'job_seeker_id')
    op.add_column('cover_letter_versions', sa.Column('seeker_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cover_letter_versions', type_='foreignkey')
    op.create_foreign_key(op.f('cover_letter_versions_seeker_id_fkey'), 'cover_letter_versions', 'agents', ['seeker_id'], ['id'])
    op.drop_column('cover_letter_versions', 'job_seeker_id')
    op.add_column('applications', sa.Column('seeker_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_seeker_id_fkey'), 'applications', 'agents', ['seeker_id'], ['id'])
    op.drop_column('applications', 'job_seeker_id')
    # ### end Alembic commands ###
