"""ORM models for simulation observability.

These models capture point-in-time state, agent reflections, and
generic events for the full simulation timeline.
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from models.base import Base, UUIDPrimaryKeyMixin


class StateSnapshot(UUIDPrimaryKeyMixin, Base):
    """Point-in-time capture of an agent's full state.

    Written at the end of every round for every agent.

    Attributes:
        run_id: Simulation run this snapshot belongs to.
        agent_id: Agent this snapshot belongs to.
        agent_type: Kind of agent, denormalized for query convenience.
        round_number: Simulation round this snapshot was taken at.
        state_json: Serialized AgentState at this point in time.
        created_at: Timestamp for ordering and debugging.
    """

    __tablename__ = "state_snapshots"
    __table_args__ = (
        UniqueConstraint(
            "run_id",
            "agent_id",
            "round_number",
            name="uq_state_snapshots_run_agent_round",
        ),
        CheckConstraint(
            "round_number >= 0",
            name="ck_state_snapshots_round_number",
        ),
    )

    run_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("simulation_runs.id"), nullable=False
    )
    agent_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=False
    )
    agent_type: Mapped[str] = mapped_column(String(20), nullable=False)
    round_number: Mapped[int] = mapped_column(Integer, nullable=False)
    state_json: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class Reflection(UUIDPrimaryKeyMixin, Base):
    """An agent's periodic self-assessment.

    Generated by prompting the agent to reflect on its situation.

    Attributes:
        run_id: Simulation run this reflection belongs to.
        agent_id: Agent who produced this reflection.
        agent_type: Kind of agent, denormalized for query convenience.
        round_number: Simulation round when generated.
        prompt_used: Full reflection prompt sent to the LLM.
        response: The agent's self-assessment in its own words.
        context_summary: Agent state summary when generated.
    """

    __tablename__ = "reflections"
    __table_args__ = (
        CheckConstraint(
            "round_number >= 0",
            name="ck_reflections_round_number",
        ),
    )

    run_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("simulation_runs.id"), nullable=False
    )
    agent_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("agents.id"), nullable=False
    )
    agent_type: Mapped[str] = mapped_column(String(20), nullable=False)
    round_number: Mapped[int] = mapped_column(Integer, nullable=False)
    prompt_used: Mapped[str] = mapped_column(Text, nullable=False)
    response: Mapped[str] = mapped_column(Text, nullable=False)
    context_summary: Mapped[str] = mapped_column(Text, nullable=False)


class Event(UUIDPrimaryKeyMixin, Base):
    """Generic event log entry for any simulation occurrence.

    Catch-all for everything that happens during a run.

    Attributes:
        run_id: Simulation run this event belongs to.
        agent_id: Agent this event relates to, or None for system
            events.
        round_number: Simulation round when this event occurred.
        event_type: What happened (e.g., application_submitted).
        details: Event-specific data as JSONB.
        created_at: Timestamp for ordering and debugging.
    """

    __tablename__ = "events"
    __table_args__ = (
        Index("ix_events_run_round", "run_id", "round_number"),
        Index("ix_events_event_type", "event_type"),
        CheckConstraint(
            "round_number >= 0",
            name="ck_events_round_number",
        ),
    )

    run_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("simulation_runs.id"), nullable=False
    )
    agent_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, ForeignKey("agents.id"))
    round_number: Mapped[int] = mapped_column(Integer, nullable=False)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    details: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
